### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by z3ntu** [Xorok/DownTheMail#2]
```
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Xml.dll

Additional information: Token EndDocument in state Document would result in an invalid XML document.
```
In line  `xmlDoc.Save(mailPath+Path.DirectorySeparatorChar+emailAddress+"_"+DateTime.Now.ToString("yyyy-MM-dd_HH-mm")+".xml");`

Reason (probably): `xmlDoc` does not get filled from my (1065) emails

**Comment by Xorok** [comment]
I know, these is one of the two exceptions that currently stops our program from working. Everything else is already finished. This problem has been fixed today, the second is a NullPointer that doesn't make any sense. Take a look at it if you want. And does the rest work like it should on Linux? It should, I used Path.DirectorySeperatorChar, etc.

**Comment by Xorok** [comment]
The problem was that the document had more than one root element.

**Comment by z3ntu** [comment]
I tested it in my virtual machine, but I'll test it in mono then
